name: Docker Image CI

on:
  pull_request:
    branches: [ "main", "dev", "staging" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
    - run: docker build . --file Dockerfile --tag dedupe-tester:$(date +%s)
    - run: docker run --rm dedupe-tester:$(date +%s) pytest
